version: '3.8'
services:
  frontend:
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    ports:
      - '3000:3000'
    volumes:
      - frontend_node_modules:/workspace/node_modules

  api:
    ports:
      - '8000:8000'
    volumes:
      - api_venv:/workspace/.venv

volumes:
  frontend_node_modules:
  api_venv:
